name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSYS2 + MinGW64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake

      - name: Configure
        shell: msys2 {0}
        run: |
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -B build -S .

      - name: Build
        shell: msys2 {0}
        run: |
          cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileEncryptor-Win-x86-64
          path: build/bin

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileEncryptor-Linux-x86-64
          path: build/bin
